

const studentList = [
    {
        firstName:"ben",
        lastName:"Stiller",
        schedule:"placeholder",
        grade: 1,
        cohort:2023
    },    
    {
        firstName:"Jenna",
        lastName:"Ortega",
        schedule:"placeholder",
        grade:2,
        cohort:2024
    },
    {
        firstName:"Benjamin",
        lastName:"Franklin",
        schedule:"placeholder",
        grade:4,
        cohort:2025
    },
    {
        firstName:"Tony",
        lastName:"Stark",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    },
    {
        firstName:"Mark",
        lastName:"Twain",
        schedule:"placeholder",
        grade:1,
        cohort:2026
    },
    {
        firstName:"Mark",
        lastName:"Hamlin",
        schedule:"placeholder",
        grade:2,
        cohort:2024
    },
    {
        firstName:"Cole",
        lastName:"Sprouce",
        schedule:"placeholder",
        grade:2,
        cohort:2026
    },
    {
        firstName:"Dylan",
        lastName:"Sprouce",
        schedule:"placeholder",
        grade:2,
        cohort:2026
    },
    {
        firstName:"Sara",
        lastName:"Jane",
        schedule:"placeholder",
        grade:3,
        cohort:2025
    },
    {
        firstName:"John",
        lastName:"Smith",
        schedule:"placeholder",
        grade:2,
        cohort:2023
    },
    {
        firstName:"Mike",
        lastName:"Myers",
        schedule:"placeholder",
        grade:1,
        cohort:2023
    },
    {
        firstName:"Stacy",
        lastName:"Ann",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    },
    {
        firstName:"Adam",
        lastName:"Sandler",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    },
    {
        firstName:"Neil",
        lastName:"Harris",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    },
    {
        firstName:"Patrick",
        lastName:"Batman",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    },
    {
        firstName:"Roger",
        lastName:"Wilco",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    },
    {
        firstName:"Simon",
        lastName:"Belmont",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    },
    {
        firstName:"Richter",
        lastName:"Belmont",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    },
    {
        firstName:"Lara",
        lastName:"Croft",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    },
    {
        firstName:"Samus",
        lastName:"Aran",
        schedule:"placeholder",
        grade:4,
        cohort:2023
    }
]

export {
    studentList
}
